import React, { useState } from 'react';
import { BarChart, PieChart, Calendar } from 'lucide-react';

export default function AnalyticsSection({ chartData }) {
  const [hoveredBar, setHoveredBar] = useState(null);
  const [hoveredPie, setHoveredPie] = useState(null);

  // Bar Chart Mock Data: Documents Created Weekly
  const barData = chartData?.weeklyDocuments || [
    { day: 'Mon', count: 12, date: 'May 21' },
    { day: 'Tue', count: 18, date: 'May 22' },
    { day: 'Wed', count: 26, date: 'May 23' },
    { day: 'Thu', count: 15, date: 'May 24' },
    { day: 'Fri', count: 32, date: 'May 25' },
    { day: 'Sat', count: 8, date: 'May 26' },
    { day: 'Sun', count: 6, date: 'May 27' }
  ];

  const maxCount = Math.max(...barData.map(d => d.count)) * 1.15; // 15% padding top
  const chartHeight = 180;
  const chartWidth = 450;
  const barWidth = 32;
  const barSpacing = (chartWidth - barWidth * barData.length) / (barData.length + 1);

  // Pie Chart Mock Data: Team Productivity share by department (Clean SaaS Greys & Blues)
  const pieData = chartData?.teamProductivity || [
    { name: 'Engineering', value: 35, color: '#0D6EFD', label: 'Code & Specs' },
    { name: 'Product', value: 25, color: '#3FA3FF', label: 'User Journeys' },
    { name: 'Marketing', value: 20, color: '#94a3b8', label: 'Client pitches' },
    { name: 'Design', value: 20, color: '#cbd5e1', label: 'UX/UI Wireframes' }
  ];

  // Helper to compute Pie Chart sector paths
  let accumulatedAngle = 0;
  const radius = 70;
  const center = 90;
  const innerRadius = 45; // Donut hole

  const pieSectors = pieData.map((slice, index) => {
    const angle = (slice.value / 100) * 360;
    const startAngle = accumulatedAngle;
    const endAngle = accumulatedAngle + angle;
    accumulatedAngle += angle;

    // Convert angles to radians
    const rad1 = (startAngle - 90) * (Math.PI / 180);
    const rad2 = (endAngle - 90) * (Math.PI / 180);

    // Compute coordinate points
    const x1 = center + radius * Math.cos(rad1);
    const y1 = center + radius * Math.sin(rad1);
    const x2 = center + radius * Math.cos(rad2);
    const y2 = center + radius * Math.sin(rad2);

    const xi1 = center + innerRadius * Math.cos(rad1);
    const yi1 = center + innerRadius * Math.sin(rad1);
    const xi2 = center + innerRadius * Math.cos(rad2);
    const yi2 = center + innerRadius * Math.sin(rad2);

    const largeArcFlag = angle > 180 ? 1 : 0;

    // SVG path string for donut slice
    const pathString = `
      M ${x1} ${y1}
      A ${radius} ${radius} 0 ${largeArcFlag} 1 ${x2} ${y2}
      L ${xi2} ${yi2}
      A ${innerRadius} ${innerRadius} 0 ${largeArcFlag} 0 ${xi1} ${yi1}
      Z
    `;

    return {
      ...slice,
      path: pathString,
      angleStart: startAngle,
      angleEnd: endAngle
    };
  });

  return (
    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
      {/* 1. Bar Chart Card */}
      <div className="glass-card p-4 border border-brand-border/60 bg-white dark:bg-slate-900 flex flex-col justify-between rounded-xl shadow-sm">
        <div>
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-1.5">
              <BarChart size={15} className="text-brand-blue" />
              <h4 className="font-bold text-xs text-brand-dark">
                Documents Created
              </h4>
            </div>
            
            <span className="flex items-center gap-1 text-[9px] font-bold text-brand-gray bg-brand-hover px-2 py-0.5 rounded border border-brand-border/50">
              <Calendar size={10} />
              <span>Weekly Logs</span>
            </span>
          </div>
          <p className="text-[11px] text-brand-gray mt-0.5 font-semibold">
            Visual statistics of documents generated by the team over the current sprint.
          </p>
        </div>

        {/* Custom SVG Bar Chart (Clean, flat) */}
        <div className="mt-4 flex justify-center relative select-none">
          <svg 
            viewBox={`0 0 ${chartWidth} ${chartHeight}`} 
            className="w-full h-full max-h-[170px]"
          >
            {/* Grid background lines */}
            {[0, 0.25, 0.5, 0.75, 1].map((ratio, idx) => {
              const yVal = chartHeight - 20 - ratio * (chartHeight - 40);
              return (
                <g key={idx}>
                  <line 
                    x1="20" 
                    y1={yVal} 
                    x2={chartWidth - 10} 
                    y2={yVal} 
                    stroke="currentColor" 
                    className="text-brand-border/40" 
                    strokeDasharray="3,3"
                    strokeWidth="1"
                  />
                  <text
                    x="5"
                    y={yVal + 3}
                    className="text-[9px] fill-brand-gray font-bold"
                  >
                    {Math.round(ratio * maxCount)}
                  </text>
                </g>
              );
            })}

            {/* Bars rendering */}
            {barData.map((data, index) => {
              const barHeight = (data.count / maxCount) * (chartHeight - 40);
              const xPos = barSpacing + index * (barWidth + barSpacing) + 10;
              const yPos = chartHeight - 20 - barHeight;
              const isHovered = hoveredBar === index;

              return (
                <g 
                  key={index}
                  onMouseEnter={() => setHoveredBar(index)}
                  onMouseLeave={() => setHoveredBar(null)}
                  className="cursor-pointer"
                >
                  {/* Clean Solid Bar with subtle border details */}
                  <rect
                    x={xPos}
                    y={yPos}
                    width={barWidth}
                    height={barHeight}
                    rx="3"
                    fill={isHovered ? "#3FA3FF" : "#0D6EFD"}
                    className="transition-all duration-150 origin-bottom"
                  />

                  {/* Day labels */}
                  <text
                    x={xPos + barWidth / 2}
                    y={chartHeight - 4}
                    textAnchor="middle"
                    className={`text-[9px] font-bold transition-colors
                      ${isHovered ? 'fill-brand-blue font-extrabold' : 'fill-brand-gray'}
                    `}
                  >
                    {data.day}
                  </text>
                </g>
              );
            })}
          </svg>

          {/* Absolute Tooltip */}
          {hoveredBar !== null && (
            <div 
              className="absolute bg-brand-dark/95 border border-brand-border/40 text-white px-2.5 py-1.5 rounded text-[10px] shadow-md flex flex-col pointer-events-none transition-all duration-100"
              style={{
                left: `${(hoveredBar / barData.length) * 80 + 10}%`,
                bottom: '80px'
              }}
            >
              <span className="font-bold text-brand-accent">{barData[hoveredBar].date}</span>
              <span className="font-semibold">{barData[hoveredBar].count} Docs Created</span>
            </div>
          )}
        </div>
      </div>

      {/* 2. Donut Chart Card */}
      <div className="glass-card p-4 border border-brand-border/60 bg-white dark:bg-slate-900 flex flex-col justify-between rounded-xl shadow-sm">
        <div>
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-1.5">
              <PieChart size={15} className="text-brand-blue" />
              <h4 className="font-bold text-xs text-brand-dark">
                Team Productivity
              </h4>
            </div>
          </div>
          <p className="text-[11px] text-brand-gray mt-0.5 font-semibold">
            Distribution of tasks completed by department.
          </p>
        </div>

        {/* Custom Donut Chart layout */}
        <div className="my-2 flex items-center justify-around gap-2 flex-wrap sm:flex-nowrap">
          {/* Chart SVG */}
          <div className="relative shrink-0 select-none">
            <svg 
              viewBox="0 0 180 180" 
              className="w-[120px] h-[120px]"
            >
              {pieSectors.map((sector, index) => {
                const isHovered = hoveredPie === index;
                return (
                  <path
                    key={index}
                    d={sector.path}
                    fill={sector.color}
                    className="transition-all duration-150 cursor-pointer origin-center"
                    style={{
                      transform: isHovered ? 'scale(1.03)' : 'scale(1)',
                      filter: isHovered ? 'brightness(1.05)' : 'none'
                    }}
                    onMouseEnter={() => setHoveredPie(index)}
                    onMouseLeave={() => setHoveredPie(null)}
                  />
                );
              })}
            </svg>

            {/* Hover details inside donut hole */}
            <div className="absolute inset-0 flex flex-col items-center justify-center pointer-events-none">
              <span className="text-[8px] text-brand-gray font-bold uppercase tracking-wider">
                {hoveredPie !== null ? pieData[hoveredPie].name : 'Total'}
              </span>
              <span className="text-base font-extrabold text-brand-dark">
                {hoveredPie !== null ? `${pieData[hoveredPie].value}%` : '100%'}
              </span>
            </div>
          </div>

          {/* Legends list */}
          <div className="flex flex-col gap-1.5 min-w-[100px]">
            {pieData.map((legend, index) => {
              const isHovered = hoveredPie === index;
              return (
                <div
                  key={index}
                  onMouseEnter={() => setHoveredPie(index)}
                  onMouseLeave={() => setHoveredPie(null)}
                  className={`flex items-start gap-1.5 p-1 rounded-lg cursor-pointer transition-all
                    ${isHovered ? 'bg-brand-hover shadow-sm' : ''}
                  `}
                >
                  <span 
                    className="w-2.5 h-2.5 rounded mt-0.5 shrink-0" 
                    style={{ backgroundColor: legend.color }}
                  />
                  <div className="min-w-0">
                    <div className="flex items-center justify-between gap-1.5">
                      <span className="text-[10px] font-bold text-brand-dark truncate">
                        {legend.name}
                      </span>
                      <span className="text-[9px] font-bold text-brand-gray">
                        {legend.value}%
                      </span>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      </div>
    </div>
  );
}
